import type { RodeoEvent } from "@/types/event";

export const sampleEvents: RodeoEvent[] = [
  {
    id: "1",
    title: "Spring Barrel Bash",
    format: "jackpot",
    disciplines: ["barrel_racing"],
    status: "registration-open",
    startDate: "2026-04-12",
    venue: "Triple R Arena",
    city: "Stephenville",
    state: "TX",
    entryFee: "$45 per event\n$10 office fee",
    description: "Open 4D barrel race with added money in all divisions.",
  },
  {
    id: "2",
    title: "High Plains Team Roping",
    format: "jackpot",
    disciplines: ["team_roping"],
    status: "upcoming",
    startDate: "2026-05-03",
    venue: "High Plains Event Center",
    city: "Amarillo",
    state: "TX",
    entryFee: "$60 per team",
    description: "Number 9 and under header / heeler roping with jackpot payout.",
  },
  {
    id: "3",
    title: "Rocky Mountain Summer Rodeo",
    format: "rodeo",
    disciplines: ["barrel_racing", "breakaway_roping", "team_roping"],
    additionalOfferings: [
      "Bull riding",
      "Mutton bustin' for kids",
      "Live country concert Saturday night",
    ],
    status: "registration-open",
    startDate: "2026-06-21",
    venue: "Rocky Ridge Arena",
    city: "Casper",
    state: "WY",
    entryFee: "$35 youth breakaway\n$45 open breakaway\n$75 open barrel",
    description: "Full weekend rodeo with timed events, roughstock, and nightly entertainment.",
  },
];
